### ISSUE TITLE
[Enhancement] Ability to toggle marker types on and off

### ISSUE THREAD

**Issue by Jamezhall** [joe-watkins/easyBCMap#2]
Hi Joe, 

Could you point in the right direction or provide a code sample to be able to toggle different marker types off and on using say a data attribute on the li like 
`data-type="employer"` vs `data-type="member"`

I tried using existing code and https://developers.google.com/maps/documentation/javascript/examples/marker-remove as an example... But struggled.

Any help would be great thanks!

**Comment by joe-watkins** [comment]
Hi @Jamezhall Unfortunately this little plugin isn't maintained any longer and doesn't support grouping. ;( You may have to roll your own for that. I'll put a note in the readme that the repo isn't maintained.
